STATIONERY_STORE = (
    "madera", "tempera", "temperas","herramientas de modelado","pegamento","pinturas","papel", "tela", "cartón", "arcilla", "vidrio", "metal", "cuero", "plástico", "cera", 
    "cuerda", "hilo", "alambre", "fieltro", "goma eva", "pintura acrílica", "pintura al óleo", 
    "pinceles", "lienzos", "papel maché", "botones", "cuentas", "lentejuelas", "cuerdas de yute", 
    "lana", "cinta adhesiva decorativa", "pegamento para manualidades", "tijeras", "cúter", 
    "perforadoras de papel", "sellos de goma", "tinta para sellos", "telas estampadas", 
    "papel de scrapbooking", "marcadores", "lápices de colores", "rotuladores", 
    "ganchos para pendientes", "cierres de joyería", "alfileres de bisutería", "anillos de salto", 
    "pegatinas", "troqueles", "pistola de silicona caliente", "perlas", "abalorios", "hojas secas", 
    "conchas marinas", "piedras pintadas", "fieltro adhesivo", "bolsas de papel kraft", 
    "papel de aluminio", "palitos de madera", "bastones de pegamento", "purpurina", 
    "purpurina adhesiva", "servilletas decorativas", "cajas de cartón", "cordones de cuero", 
    "papel de lija", "goma laca", "aceite de linaza", "cera para velas", "velas", 
    "papeles de origami", "arena de colores", "cuentas de cristal", "botellas de vidrio", 
    "recipientes de cerámica", "tableros de corcho", "tela de encaje", "fieltro adhesivo", 
    "pintura para tela", "cajas de madera", "pajitas de papel", "espejos pequeños", 
    "periódicos viejos", "papel de aluminio", "envases de plástico", "moldes para resina", 
    "resina epoxi", "pigmentos para resina", "botellas de spray", "tuberías de PVC", 
    "cajas de huevos", "hojas de palma", "ramas secas", "bastidores de bordado", 
    "lana de fieltro", "hojas de acetato", "arcilla polimérica", "moldes de silicona", 
    "fieltro estampado", "cáscaras de huevo", "paletas de madera", "corcho", "cintas de raso", 
    "abalorios de madera", "cáñamo", "paja", "papel pergamino", "esponjas", "tela de arpillera", 
    "papel adhesivo", "hilo de algodón", "papeles texturizados", "tuberías de papel", 
    "cuero sintético", "correas de cuero", "tinta para tela", "sellos de tinta para tela", 
    "velcro", "plantillas para estarcido", "botellas de plástico recicladas", "tapones de corcho", 
    "cajas de fósforos", "clips de papel", "páginas de libros viejos", "sellos de cera", 
    "hojas de goma espuma", "bolsas de tela", "marcadores permanentes", "pegamento en barra", 
    "botellas de pintura en spray", "adornos de madera", "pintura de pizarra", 
    "bolsas de papel de estraza", "algodón", "pelotas de ping-pong", "palitos de helado", 
    "ojos móviles", "cartulina", "papel de regalo", "cubiertos de plástico", 
    "tazas de plástico", "cucharas de madera", "mariposas secas", "papel de lija", 
    "globos", "cartulina holográfica", "pañuelos de papel", "telarañas artificiales", 
    "latas de conserva", "alambres de colores", "papeles de colores", "gafas de plástico", 
    "encaje", "guantes de látex", "cartones de huevo de cartón", "botellas de vidrio recicladas", 
    "moldes para velas", "hojas de aluminio", "bolsas de plástico", "trozos de tela vaquera", 
    "muestras de pintura", "discos de vinilo", "pintura para pizarra", "cáscaras de nuez", 
    "clips para la ropa", "palitos de bambú", "perchas de alambre", "tarjetas de felicitación", 
    "hojas de oro", "papel de aluminio dorado", "cajas de cerillas", "ruedas de juguete", 
    "tazas de cartón", "jarrones de terracota", "bolsas de arena")

HARDWARE_STORE = (
    "tornillos", "tuercas", "arandelas", "clavos", "martillo", "destornillador", "llaves inglesas", 
    "llave ajustable", "cinta métrica", "alicates", "sierra", "caladora", "cepillos para madera", 
    "lijas", "taladro", "brocas", "nivel", "cinta adhesiva", "pegamento para madera", 
    "pintura para metal", "pintura para madera", "pinceles", "rodillos de pintura", 
    "cubetas para pintura", "masilla para madera", "bisagras", "cerraduras", 
    "cadenas", "grapas", "clavadoras", "llaves de tubo", "tubo de PVC", 
    "codos de PVC", "te de PVC", "union de PVC", "tubería de cobre", 
    "conexiones de cobre", "cinta de teflón", "sellador para tuberías", 
    "pegamento para PVC", "cables eléctricos", "enchufes", "interruptores", 
    "bombillas", "focos", "cables de extensión", "enchufes múltiples", 
    "cinta eléctrica", "tubos fluorescentes", "interruptores de luz", 
    "timbres de puerta", "cerraduras eléctricas", "sensores de movimiento", 
    "baterías", "destornilladores eléctricos", "taladros inalámbricos", 
    "sierras circulares", "sierras de calar", "clavadoras eléctricas", 
    "lijadoras eléctricas", "herramientas rotativas", "niveles láser", 
    "cadenas de motosierra", "aceite para motosierra", "herramientas para jardín", 
    "mangueras de jardín", "aspersores", "parrillas para barbacoa", 
    "carbón para barbacoa", "bolsas de basura", "contenedores de basura", 
    "escobas", "recogedores", "cubos", "plumones", "silicona", 
    "selladores", "herramientas para pintar", "andamios", 
    "escaleras", "guantes de trabajo", "gorros de seguridad", 
    "lentes de seguridad", "botas de trabajo", "máscaras de polvo", 
    "extintores", "alarmas de humo", "candados", "cerrojos", 
    "bisagras para puertas", "cierres de puertas", "cinturones de seguridad", 
    "casquillos para focos", "lámparas de trabajo", "escaleras telescópicas", 
    "escaleras de tijera", "barras de refuerzo", "alicates de punta", 
    "destornilladores de precisión", "sargentos", "pistolas de calor", 
    "sierras de mano", "llaves allen", "compresores de aire", 
    "máquinas de soldar", "alambre para soldar", "caretas de soldar", 
    "discos abrasivos", "mascarillas de seguridad", "andamios móviles", 
    "escaleras extensibles", "tacos para pared", "tornillos para madera", 
    "tornillos para metal", "tacos para concreto", "remaches", 
    "cadenas para herramientas", "taladros de percusión", 
    "martillos demoledores", "cintas transportadoras", "rampas para autos", 
    "mesas de trabajo", "sierras de mesa", "brocas para concreto", 
    "discos de corte", "carretillas", "hachas", "palas", "rastreles", 
    "regaderas", "rastrillos", "pértigas para podar", "cuerdas", 
    "baldosas", "cuchillas para cortacésped", "baterías para herramientas", 
    "filtros para aspiradoras", "escaleras de mano", "motosierras", 
    "sierras de cadena", "linternas", "candelabros", "molduras", 
    "calentadores de agua", "calentadores eléctricos", 
    "calentadores de gas", "tubos de gas", "radiadores", 
    "mallas metálicas", "tornillos para yeso", "tacos para yeso", 
    "canaletas para agua", "bombas de agua", "tuberías de agua", 
    "válvulas de agua", "grifos", "llaves de paso", "fregaderos", 
    "tornillos para pladur", "tacos para pladur", "muelas abrasivas", 
    "máquinas pulidoras", "protectores auditivos", "escaleras plegables", 
    "tubos de desagüe", "sifones", "baldosas para suelos", 
    "azulejos", "selladores de silicona", "protectores de esquinas", 
    "tornillos para metal y madera", "cuerdas para tendedero", 
    "herramientas de medición", "brújulas", "destornilladores de impacto", 
    "herramientas para fontanería", "llaves para tubos", 
    "llaves de fontanero", "cinta de medir", "muelles de compresión", 
    "muelles de tracción", "pistolas de clavos", "brocas para metal", 
    "mallas de sombra", "ceras para madera", "pinceles para esmalte", 
    "barnices", "mallas antideslizantes", "gomas para puertas", 
    "ruedas para muebles", "tacos para sillas", "perfiles de aluminio", 
    "escaleras de aluminio", "rejas de seguridad", "cerraduras de seguridad", 
    "tacos expansivos", "tornillos autorroscantes", 
    "machos de roscar", "sierras de calar para madera", 
    "sierras de calar para metal", "fresas para madera", 
    "fresas para metal", "fresas para concreto", 
    "cuchillas para sierras circulares", "tuercas de mariposa", 
    "tornillos de fijación", "tornillos para plástico", 
    "placas de pladur", "tornillos para hormigón", 
    "tacos para hormigón", "tejidos metálicos", 
    "cintas adhesivas de doble cara", "herramientas para electricistas", 
    "conectores eléctricos", "placas de anclaje", 
    "muelles para puertas", "tornillos de banco", 
    "discos de desbaste", "pistolas de pintura", 
    "mascarillas antigás", "chalecos reflectantes", 
    "papel de lija para madera", "papel de lija para metal", 
    "papel de lija para concreto", "brochas para pintura", 
    "pinceles para pintura", "poleas", "engranajes", 
    "cadenas para motosierras", "guantes anticorte", 
    "sierras de sable", "carretillas de mano", 
    "escaleras de aluminio extensibles", 
    "remachadoras", "tornillos para placa de yeso", 
    "tuercas para placa de yeso", "fijaciones para techos", 
    "escuadras para estanterías", "tornillos para terrazas", 
    "sillas plegables", "cadenas de acero", "eslingas", 
    "grúas", "caballetes", "tacos para tabiques", 
    "tornillos para tabiques", "brocas para vidrio", 
    "cortadoras de azulejos", "tornillos para tejados", 
    "cuerdas elásticas", "tacos para baldosas", 
    "tornillos para baldosas", "máquinas de cortar cerámica", 
    "gafas de protección", "escaleras telescópicas de aluminio", 
    "correas de sujeción", "mallas para construcción", 
    "alicates para cercas", "tornillos para vallas", 
    "tacos para vallas", "bidones para productos químicos", 
    "cinturones de carga", "escaleras de mano de fibra de vidrio", 
    "tubos de ventilación", "extractores de aire", 
    "cintas transportadoras de goma", "tacos para plástico", 
    "tornillos para plástico", "clavos para plástico", 
    "tacos para plástico", "cierres para ventanas", 
    "topes para puertas", "carritos de herramientas", 
    "cintas transportadoras de metal", "tornillos para metal y madera", 
    "tornillos para metal y plástico", "fibras de vidrio", 
    "selladores de juntas", "tornillos para muebles", 
    "escuadras para muebles", "cerraduras para muebles", 
    "bisagras para muebles", "tacos para muebles", 
    "tornillos para techos de chapa")

SUPERMARKET = (
    "Arroz", "Fideos", "Aceite de oliva", "Sal", "Azúcar", "Huevos", "Leche", "Queso", "Pan", "Pollo", 
    "Carne de res", "Pescado", "Frutas", "Verduras", "Tomates enlatados", "Sopa enlatada", "Galletas", 
    "Cereal", "Yogur", "Mantequilla", "Papel higiénico", "Pañuelos de papel", "Detergente para ropa", 
    "Jabón de manos", "Pasta de dientes", "Cepillo de dientes", "Agua embotellada", "Refrescos", 
    "Café", "Té", "Vino", "Cerveza", "Pizza congelada", "Helado", "Caramelos", "Chips", "Salsa de tomate", 
    "Mayonesa", "Mostaza", "Ketchup", "Vinagre", "Salsa de soja", "Salsa picante", "Hierbas y especias", 
    "Aceitunas", "Enlatados de atún", "Sopa instantánea", "Salsa para pasta", "Miel", "Cacahuetes", 
    "Almendras", "Chocolate", "Café instantáneo", "Arándanos congelados", "Pimientos enlatados", 
    "Aceitunas rellenas", "Papel de aluminio", "Film transparente", "Bolsas de basura", "Bolsas de congelador", 
    "Cajas de cereales", "Cajas de jugo", "Lechuga", "Pimientos", "Cebollas", "Ajo", "Patatas", "Zanahorias", 
    "Manzanas", "Plátanos", "Uvas", "Naranjas", "Limones", "Aguacates", "Piñas", "Melones", "Fresas", 
    "Mantequilla de cacahuate", "Mermelada", "Panecillos", "Papel de cocina", "Servilletas de papel", 
    "Aceitunas verdes", "Aceitunas negras", "Enlatados de maíz", "Salsa de enchilada", "Arándanos", 
    "Compota de manzana", "Cereal de avena", "Crema agria", "Jugo de naranja", "Jugo de manzana", 
    "Pan integral", "Pasta integral", "Leche de almendras", "Leche de soja", "Leche de avena", 
    "Queso parmesano", "Queso cheddar", "Queso suizo", "Queso mozzarella", "Queso feta", 
    "Yogur griego", "Yogur de vainilla", "Salsa de barbacoa", "Salsa de pesto", "Aceitunas kalamata", 
    "Salsa Worcestershire", "Cereal de arroz", "Cereal de trigo", "Cereal de maíz", "Salsa de pescado", 
    "Salsa de teriyaki", "Hummus", "Huevos de codorniz", "Leche evaporada", "Leche condensada", 
    "Alubias enlatadas", "Garbanzos enlatados", "Sopa de lentejas enlatada", "Sopa de guisantes enlatada", 
    "Sopa de champiñones enlatada", "Alubias secas", "Arroz integral", "Pasta de trigo integral", 
    "Galletas integrales", "Pan integral de centeno", "Pan integral de avena", "Aceite de canola", 
    "Aceite de coco", "Aceite vegetal", "Aceite de girasol", "Aceitunas españolas", "Chips de tortilla", 
    "Salsa de queso", "Queso azul", "Queso de cabra", "Salsa de arándanos", "Panecillos de hamburguesa", 
    "Panecillos de perrito caliente", "Galletas saladas", "Jamón", "Salchichas", "Salsa de tomate orgánica", 
    "Salsa de tomate con ajo", "Salsa de tomate con albahaca", "Salsa de tomate con champiñones", 
    "Salsa de tomate con queso", "Salsa de tomate con hierbas", "Café descafeinado", "Galletas sin gluten", 
    "Pan sin gluten", "Leche sin lactosa", "Yogur sin lactosa", "Sopa baja en sodio", "Sopa baja en grasas", 
    "Mantequilla baja en grasas", "Cereal bajo en azúcar", "Cereal bajo en grasas", "Cereal bajo en calorías", 
    "Galletas bajas en calorías", "Galletas bajas en grasas", "Yogur bajo en grasas", "Yogur bajo en calorías", 
    "Queso bajo en grasa", "Queso bajo en calorías", "Leche baja en grasa", "Leche baja en calorías", 
    "Leche sin grasa", "Leche sin calorías", "Helado bajo en grasa", "Helado bajo en calorías", 
    "Salsa baja en calorías", "Salsa baja en grasa", "Salsa sin calorías", "Salsa sin grasa", "Mantequilla sin sal", 
    "Mantequilla sin calorías", "Mantequilla baja en calorías", "Pasta sin gluten", "Pasta sin calorías", 
    "Pasta integral sin calorías", "Galletas sin calorías", "Galletas sin grasas", "Galletas sin gluten", 
    "Chocolates sin azúcar", "Chocolates sin grasas", "Chocolates sin lactosa", "Chocolates sin gluten", 
    "Caramelos sin azúcar", "Caramelos sin grasas", "Caramelos sin lactosa", "Caramelos sin gluten", 
    "Refrescos sin calorías", "Refrescos sin azúcar", "Refrescos sin cafeína", "Refrescos sin gluten", 
    "Cerveza sin alcohol", "Cerveza sin gluten", "Vino sin alcohol", "Vino sin azúcar", "Vino sin gluten", 
    "Pan sin gluten", "Pan sin calorías", "Pan integral sin gluten", "Pan integral sin calorías", 
    "Pan integral sin azúcar", "Pan integral sin lactosa", "Pan integral sin gluten y sin calorías", 
    "Salsa sin azúcar", "Salsa sin grasas", "Salsa sin calorías", "Salsa sin gluten", "Miel sin azúcar", 
    "Miel sin calorías", "Miel sin grasas", "Miel sin gluten", "Cereal sin azúcar", "Cereal sin grasas", 
    "Cereal sin calorías", "Cereal sin gluten", "Yogur sin azúcar", "Yogur sin grasas", "Yogur sin lactosa", 
    "Yogur sin gluten", "Leche sin azúcar", "Leche sin grasas", "Leche sin lactosa", "Leche sin gluten", 
    "Queso sin azúcar", "Queso sin grasas", "Queso sin lactosa", "Queso sin gluten", "Sopa sin calorías", 
    "Sopa sin grasas", "Sopa sin gluten", "Sopa sin lactosa", "Sopa sin azúcar", "Mantequilla sin azúcar", 
    "Mantequilla sin calorías", "Mantequilla sin grasas", "Mantequilla sin lactosa", "Mantequilla sin gluten", 
    "Aceitunas sin azúcar", "Aceitunas sin calorías", "Aceitunas sin grasas", "Aceitunas sin lactosa", 
    "Aceitunas sin gluten", "Chips sin azúcar", "Chips sin calorías", "Chips sin grasas", "Chips sin lactosa", 
    "Chips sin gluten", "Salsa de tomate sin azúcar", "Salsa de tomate sin calorías", "Salsa de tomate sin grasas", 
    "Salsa de tomate sin lactosa", "Salsa de tomate sin gluten", "Pasta sin azúcar", "Pasta sin calorías", 
    "Pasta sin grasas", "Pasta sin lactosa", "Pasta sin gluten", "Galletas sin azúcar", "Galletas sin calorías", 
    "Galletas sin grasas", "Galletas sin lactosa", "Galletas sin gluten", "Café sin azúcar", "Café sin calorías", 
    "Café sin grasas", "Café sin lactosa", "Café sin gluten", "Té sin azúcar", "Té sin calorías", 
    "Té sin grasas", "Té sin lactosa", "Té sin gluten", "Vino sin azúcar", "Vino sin calorías", "Vino sin grasas", 
    "Vino sin lactosa", "Vino sin gluten", "Cerveza sin azúcar", "Cerveza sin calorías", "Cerveza sin grasas", 
    "Cerveza sin lactosa", "Cerveza sin gluten", "Pizza sin azúcar", "Pizza sin calorías", "Pizza sin grasas", 
    "Pizza sin lactosa", "Pizza sin gluten", "Helado sin azúcar", "Helado sin calorías", "Helado sin grasas", 
    "Helado sin lactosa", "Helado sin gluten", "Caramelos sin azúcar")

CAKE_SHOP = (
    "harina", "azúcar", "huevos", "mantequilla", "levadura", "esencia de vainilla", "chocolate", 
    "cacao en polvo", "leche", "crema de leche", "azúcar glas", "almendras", "nueces", "avena", 
    "fondant", "colorantes alimentarios", "glaseado real", "frutas confitadas", "frutas secas", 
    "merengue", "extracto de almendra", "extracto de limón", "extracto de naranja", "almidón de maíz", 
    "azúcar moreno", "azúcar mascabado", "canela", "jengibre en polvo", "clavos de olor", 
    "nuez moscada", "bicarbonato de sodio", "polvo de hornear", "sal", "aceite vegetal", 
    "aceite de coco", "esencia de menta", "esencia de coco", "papel pergamino", "papel manteca", 
    "moldes para cupcakes", "moldes para pasteles", "moldes para galletas", "cortadores de galletas", 
    "boquillas para manga pastelera", "manga pastelera", "cápsulas para cupcakes", "bases para pasteles", 
    "rodillo de amasar", "cepillo de repostería", "pinceles para fondant", "cortadores de fondant", 
    "estecas para fondant", "rodillo texturizador", "tapetes para amasar", "bandejas para horno", 
    "papel encerado", "báscula de cocina", "termómetro de cocina", "espátulas", "batidores", 
    "varillas para batir", "tamices", "espolvoreadores", "cucharas medidoras", "cortadores de masa", 
    "estrellas de azúcar", "confites de colores", "perlitas de azúcar", "sprinkles", "polvo comestible dorado", 
    "papel de azúcar", "figuras de mazapán", "betún", "crema chantilly", "queso crema", 
    "crema agria", "frutas frescas", "gelatina", "sirope de chocolate", "sirope de fresa", 
    "sirope de arce", "glaseado de queso crema", "mermelada", "crema de avellanas", "galletas decorativas", 
    "confites de chocolate", "palitos para cake pops", "molde para cake pops", "fresas frescas", 
    "arándanos", "kiwi", "plátano", "mango", "cerezas", "uvas", "manzanas", "peras", 
    "piña", "duraznos", "coco rallado", "malvaviscos", "crema de cacao", "crema de cacahuate", 
    "caramelo líquido", "salsa de caramelo", "frutas deshidratadas", "galletas trituradas", 
    "cereal de arroz inflado", "queso mascarpone", "huevitos de chocolate", "dulces de menta", 
    "fideos de chocolate", "mazapán", "huesitos de merengue", "dulce de leche", "crema de almendras", 
    "almendra laminada", "pistachos", "malvaviscos de colores", "betún de colores", "caramelos duros", 
    "cacao nibs", "chispas de caramelo", "decoraciones de azúcar", "sacabolas de melón", 
    "cucharas para helado", "crema de pistacho", "perlas comestibles", "gotas de chocolate", 
    "pasta de avellanas", "almendras caramelizadas", "frutas en almíbar", "cáscaras de limón confitadas", 
    "cáscaras de naranja confitadas", "frutas glaseadas", "turrón", "candied ginger", 
    "esencia de almendra amarga", "cáscara de huevo en polvo", "maracuyá", "granillo de colores", 
    "queso ricotta", "candies de menta", "grosellas", "vinagre balsámico", "nata montada", 
    "maracuyá en pulpa", "frutas en almíbar", "grosellas", "vinagre balsámico", "nata montada", 
    "maracuyá en pulpa", "salsa de frambuesa", "licor de cereza", "mantequilla clarificada", 
    "chocolate blanco", "chocolate con leche", "chocolate negro", "cereal de avena", 
    "mermelada de fresa", "mermelada de albaricoque", "crema de cacahuate con trozos", 
    "galletas maría", "galletas de chocolate", "galletas de avena", "galletas de jengibre", 
    "galletas de canela", "galletas de almendra", "galletas de coco", "galletas de vainilla", 
    "galletas de avellanas", "galletas de maíz", "galletas de pistacho", "galletas de limón", 
    "galletas de naranja", "galletas de fresa", "galletas de frutas", "galletas de nuez", 
    "galletas de almendra", "galletas de café", "galletas de té", "galletas de mantequilla", 
    "galletas de avena y pasas", "galletas de miel", "galletas de piñones", "galletas de coco", 
    "galletas de avellanas", "galletas de maíz", "galletas de pistacho", "galletas de limón", 
    "galletas de naranja", "galletas de fresa", "galletas de frutas", "galletas de nuez", 
    "galletas de almendra", "galletas de café", "galletas de té", "galletas de mantequilla", 
    "galletas de avena y pasas", "galletas de miel", "galletas de piñones", "galletas de especias", 
    "galletas de avena y chocolate", "galletas de nuez moscada", "galletas de vainilla y cacao", 
    "galletas de miel y almendras", "galletas de arándanos", "galletas de nata", "galletas de coco y nueces", 
    "galletas de avellanas y pasas", "galletas de almendra y frutas confitadas", "galletas de avena y pasas", 
    "galletas de miel", "galletas de piñones", "galletas de especias", "galletas de avena y chocolate", 
    "galletas de nuez moscada", "galletas de vainilla y cacao", "galletas de miel y almendras", 
    "galletas de arándanos", "galletas de nata", "galletas de coco y nueces", "galletas de avellanas y pasas", 
    "galletas de almendra y frutas confitadas", "pastillas de chocolate", "chips de chocolate", 
    "trocitos de chocolate blanco", "chocolate en gotas", "chocolate fundido", "chocolate temperado", 
    "galletas de chocolate blanco", "galletas de chocolate con leche", "galletas de chocolate negro", 
    "galletas de chocolate amargo", "galletas de chocolate con almendras", "galletas de chocolate con avellanas", 
    "galletas de chocolate con caramelo", "galletas de chocolate con frutas", "galletas de chocolate con menta", 
    "galletas de chocolate con nueces", "galletas de chocolate con pasas", "galletas de chocolate con trocitos", 
    "galletas de chocolate con trozos", "galletas de chocolate con almendras y pasas", 
    "galletas de chocolate con nueces y caramelo", "galletas de chocolate con arándanos y frutas", 
    "galletas de chocolate con pistachos y almendras", "galletas de chocolate con avellanas y pasas", 
    "galletas de chocolate con almendra y frutas confitadas", "pastillas de chocolate", "chips de chocolate", 
    "trocitos de chocolate blanco", "chocolate en gotas", "chocolate fundido", "chocolate temperado", 
    "galletas de chocolate blanco", "galletas de chocolate con leche", "galletas de chocolate negro", 
    "galletas de chocolate amargo", "galletas de chocolate con almendras", "galletas de chocolate con avellanas", 
    "galletas de chocolate con caramelo", "galletas de chocolate con frutas", "galletas de chocolate con menta", 
    "galletas de chocolate con nueces", "galletas de chocolate con pasas", "galletas de chocolate con trocitos", 
    "galletas de chocolate con trozos", "galletas de chocolate con almendras y pasas")

TECHNOLOGY_STORE = (
    "computador","pc","computadora portátil", "teléfono inteligente", "tableta", "ratón", "teclado", "monitor", 
    "cable USB", "cargador", "auriculares", "altavoces", "disco duro externo", "memoria USB", 
    "tarjeta de memoria", "router", "módem", "impresora", "escáner", "cámara web", 
    "micrófono", "dispositivo de almacenamiento en la nube", "batería externa", "adaptador de corriente", 
    "laptop stand", "funda para portátil", "soporte para teléfono", "protector de pantalla", 
    "limpiador de pantalla", "luz LED para teclado", "candado de seguridad para portátil", 
    "mouse pad", "almohadilla de muñeca", "teclado mecánico", "mouse inalámbrico", 
    "alfombrilla de carga inalámbrica", "soporte para tableta", "estuche para auriculares", 
    "estuche para cables", "estuche para cargador", "mochila para portátil", "base para portátil", 
    "teclado Bluetooth", "ratón Bluetooth", "base de carga para teléfono", "adaptador USB-C", 
    "hub USB", "pantalla adicional para portátil", "lentes para bloquear luz azul", 
    "soporte para monitor", "kit de herramientas para reparación de dispositivos", "pulsera antiestática", 
    "placa de circuito", "componentes electrónicos", "fuente de alimentación", "tarjeta madre", 
    "procesador", "tarjeta gráfica", "memoria RAM", "almacenamiento SSD", "almacenamiento HDD", 
    "sistema operativo", "software de seguridad", "software de productividad", "software de diseño", 
    "software de desarrollo", "auriculares inalámbricos", "teclado inalámbrico", "altavoces Bluetooth", 
    "reloj inteligente", "gafas de realidad virtual", "dron", "cámara digital", "trípode", 
    "estabilizador de imagen", "lente de cámara", "batería recargable", "cable HDMI", 
    "cable de red", "luz LED para fotografía", "cámara de seguridad", "dispositivo de transmisión", 
    "consola de videojuegos", "controlador de juegos", "auriculares gaming", "teclado gaming", 
    "mouse gaming", "silla gaming", "mesa para juegos", "soporte para auriculares", 
    "soporte para controlador de juegos", "pantalla curva", "teclado mecánico gaming", 
    "mouse pad gaming", "cámara de vigilancia", "smartwatch", "pulsera de actividad", 
    "sensor de fitness", "dispositivo de seguimiento de sueño", "pantalla táctil", 
    "panel solar", "batería solar", "cargador solar", "termómetro digital", "escáner de código de barras", 
    "impresora 3D", "filamento de impresora 3D", "soporte para monitor ajustable", 
    "lámpara LED de escritorio", "tarjeta de red", "memoria flash", "micrófono USB", 
    "lápiz digital", "tableta gráfica", "software de edición de video", "software de edición de fotos", 
    "soporte para teléfono ajustable", "estación de carga múltiple", "adaptador de corriente USB", 
    "teclado plegable", "ratón plegable", "pantalla plegable", "dispositivo de realidad aumentada", 
    "adaptador Bluetooth", "mini proyector", "disco duro portátil", "teclado numérico", 
    "repetidor Wi-Fi", "luz LED para fotografía", "estuche para disco duro", "cable de carga magnético", 
    "soporte para tablet ajustable", "luz USB LED", "soporte para teléfono plegable", 
    "cargador inalámbrico rápido", "organizador de cables", "bolsa de viaje para dispositivos", 
    "caja de almacenamiento para accesorios", "almohadilla térmica para portátil", 
    "estuche para tarjetas de memoria", "tarjeta de sonido externa", "soporte para auriculares con carga inalámbrica", 
    "soporte para laptop ajustable", "soporte para tablet plegable", "soporte para monitor con cajón", 
    "luz LED para teclado USB", "soporte para teléfono con carga inalámbrica", 
    "estación de carga para múltiples dispositivos", "caja de seguridad para dispositivos electrónicos", 
    "software de gestión de proyectos", "software de análisis de datos", "software de inteligencia artificial", 
    "software de aprendizaje automático", "software de diseño de circuitos", "software de modelado 3D", 
    "software de simulación", "software de desarrollo de aplicaciones", "software de gestión de redes", 
    "software de animación", "software de edición de música", "software de diseño gráfico", 
    "software de renderizado 3D", "software de realidad virtual", "software de seguridad informática", 
    "software de navegación GPS", "software de reconocimiento facial", "software de reconocimiento de voz", 
    "software de análisis de big data", "software de gestión de inventario", "software de gestión de proyectos ágiles", 
    "software de diseño de interfaces de usuario", "software de edición de código", "software de creación de presentaciones", 
    "software de gestión de documentos", "software de desarrollo de videojuegos", "software de optimización de sistemas", 
    "software de simulación de vuelo", "software de análisis financiero", "software de diseño de moda", 
    "software de gestión de recursos humanos", "software de diseño de interiores", "software de análisis de mercado", 
    "software de gestión de relaciones con clientes", "software de diseño de logotipos", "software de análisis de redes sociales", 
    "software de gestión de eventos", "software de diseño de tarjetas de visita", "software de gestión de tareas", 
    "software de análisis de riesgos", "software de edición de vídeo en 360 grados", "software de optimización de SEO", 
    "software de edición de sonido", "software de gestión de almacenes", "software de análisis de datos climáticos", 
    "software de creación de música electrónica", "software de modelado de personajes en 3D", "software de análisis de espectro de audio", 
    "software de desarrollo de aplicaciones móviles", "software de diseño de logotipos animados", "software de creación de cómics digitales", 
    "software de creación de gráficos de movimiento", "software de análisis de partículas", "software de optimización de energía", 
    "software de gestión de proyectos de construcción", "software de análisis de comportamiento del consumidor", "software de simulación de terremotos", 
    "software de reconocimiento de patrones", "software de gestión de crisis", "software de diseño de circuitos impresos", 
    "software de gestión de flotas", "software de análisis de precios de acciones", "software de diseño de jardines", 
    "software de creación de cuestionarios en línea", "software de simulación de procesos químicos", "software de gestión de calidad", 
    "software de diseño de empaques", "software de análisis de rendimiento de aplicaciones", "software de optimización de tráfico", 
    "software de gestión de inventario de restaurantes", "software de análisis de patrones de tráfico", "software de diseño de redes de comunicación", 
    "software de simulación de circuitos eléctricos", "software de gestión de activos de TI", "software de análisis de voz", 
    "software de diseño de logotipos 3D", "software de análisis de impacto ambiental", "software de simulación de guerra", 
    "software de optimización de rutas de entrega", "software de gestión de proyectos de investigación", "software de análisis de movimientos sísmicos", 
    "software de diseño de etiquetas", "software de gestión de proyectos de software", "software de análisis de sonido ambiental", 
    "software de optimización de redes eléctricas", "software de simulación de vuelo espacial", "software de análisis de expresiones faciales", 
    "software de gestión de proyectos de construcción de infraestructuras", "software de análisis de datos genéticos", "software de diseño de aviones", 
    "software de gestión de procesos empresariales", "software de análisis de vibraciones", "software de optimización de procesos de fabricación", 
    "software de simulación de procesos de fabricación", "software de análisis de redes neuronales", "software de gestión de proyectos de desarrollo de productos", 
    "software de análisis de fenómenos meteorológicos", "software de diseño de productos", "software de gestión de proyectos de desarrollo de software", 
    "software de análisis de interacciones en redes sociales", "software de optimización de procesos químicos", "software de simulación de reacciones químicas", 
    "software de análisis de comportamiento de consumidores en línea", "software de diseño de ropa", "software de gestión de proyectos de construcción de edificios", 
    "software de análisis")